project:
  type: website
  # output-dir: docs

website:
  announcement:
    icon: cone-striped
    dismissable: true
    content: |
      "Vous lisez une version non finalisée d'un blog actuellement en cours d'élaboration"
    type: primary
    position: below-navbar
  title: "Mon vestibule ..."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    lang: "fr"
    theme: cosmo
    css: styles.css



